### ISSUE TITLE
Integrate code climate with travis

### ISSUE THREAD

**Issue by cressie176** [guidesmiths/systemic#35]
@UlisesGascon 

Looks like you've configured travis to automatically publish tagged builds. It would be really good to do this with the codeclimate metrics too, otherwise I think that npm search will start penalising systemic because there won't be a set of code quality metrics for the release.

Currently I do this by keeping a .gitignored file called .codeclimate locally, containing the code climate token. It's [sourced](https://github.com/guidesmiths/systemic/blob/master/package.json#L10) before running the climate metrics.

**Comment by UlisesGascon** [comment]
I love the idea! Can we use environmental variables to inject the token in Travis like we do for NPM tokens?

**Comment by cressie176** [comment]
Yes

**Comment by cressie176** [comment]
We should move to github actions - better than travis and you can specify repo level secrets for codeclimate and organisation level secrets for npm publish

**Comment by cressie176** [comment]
GitHub actions set up. We just need the organisation secrets.
