### ISSUE TITLE
Improve errors on start up

### ISSUE THREAD

**Issue by feliun** [guidesmiths/systemic#4]
When a systemic starts with some missing dependencies the error that bubbles up is not very clear:

```
TypeError: Cannot match against 'undefined' or 'null'
```

Ideally you want to see what component is failing and with which dependency.

**Comment by cressie176** [comment]
Was this caused by the require-all bug you found? There's a test for reporting missing dependencies so I assume so.

**Comment by cressie176** [comment]
Fixed.
